---

- name: "Create the apache wordpress config file"
  template:
    src: wordpress.conf
    dest: /etc/apache2/sites-available/wordpress.conf
    owner: root
    group: root
    mode: '0644'

- name: "Disable the default apache2 module"
  apache2_module:
    state: absent
    name: 000-default

- name: "Enable the wordpress apache module"
  apache2_module:
    state: present
    name: wordpress
